# Exercises during the lectures of computational macroeconomics by Junior Professor Lustenhower @Uni Heidelberg in the wintersemester 2021

One comit per lecture exercise. The assignments are done in their own notebook and transfered to .py file for submission/grading.

## Lecture 1 - Lists/loops/if-clause/general stuff

Consider the following list:
    
    x = [1,8,3,4,7,6,2,5]

a) Create a new list y with the same length as x and fill it with zeros only.

Next, identify all integers in x that are < 5 and assign a value 1 at the
same index in the new list y whenever this condition is true and a value 0
when it is not. 
    
Finally, print y.


b) Identify all integers in x that are < 5 and store them, in the same order
as before, in a new list z. 

Print z.

c) Identify all integers in x that are < 3 or > 5 and store them, in the same
order as before, in a new list w.

d) Take the list w from the previous exercise and sort its entries in ascending
order - by the way, you are not allowed to use list.sort(). Print the
resulting list. 

Hints: use the unpythonic for-loops with explicit indices.
Then check whether the k-th (or whatever your indice is) entry in w is
larger than the k+1-th entry. If this is the case, you need to switch them.
This can be done with the following code line:
    
    w[k],w[k+1] = w[k+1],w[k]

In [8]:
# a)

x = [1,8,3,4,7,6,2,5]
y = []
for i in x:
     y.append(0)

assert(len(x) == len(y))
print(y)

[0, 0, 0, 0, 0, 0, 0, 0]


In [15]:
# b)
z = []
for i in x:
    if i < 5:
        z.append(i)

print(z)

[1, 3, 4, 2]


In [16]:
# c)
w = []
for i in x:
    if i < 3 or i > 5:
        w.append(i)

print(w)

[1, 8, 7, 6, 2]


## Lecture 2: Numpy

### Difference between np.array and lists

- Create two lists MyList1 and MyList2, where the length of both lists
equals 7. Then perform addition of both lists and print their sum.
- Create MyArray1 and MyArray2. Each of them should contain 8 elements.
Print the result of addition of values of both arrays. What is the difference
when you add values of lists and arrays?
- Make the following multiplication: MyList1 * 5 and print the result.
- Implement the following steps and explain what happens: MyArray2 * 5

In [15]:
import numpy as np

mylist1 = [0,1,2,3,4,5,6]
mylist2 = [4,5,6,7,8,9,0]

# list addition
result_list = [0] * len(mylist1)

for i in range(len(mylist1)):
    result_list[i] = mylist1[i] + mylist2[i]

print('list addition: ', result_list)

# array addition
myarray1 = np.random.random(8)
myarray2 =  np.random.random(8)

result_array = myarray1 + myarray2
print('array addition: ', result_array)

# list multiplication
print('list multiplication: ', mylist1 * 5)
# the list-elements are repeated 5 times

# array multiplication:
print('array multiplication', myarray2 * 5 )
# each elemt is multiplied by 5

list addition:  [4, 6, 8, 10, 12, 14, 6]
array addition:  [0.56596378 1.38682127 1.6534851  0.37488276 0.94803524 0.43772179
 1.03319426 1.12705078]
list multiplication:  [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]
array multiplication [0.52940893 2.29853541 3.99205086 0.36090157 3.75238696 0.62741359
 2.91139796 0.76677422]


In [18]:
A = [3, 4, 6]
B = A
B [1] = 7
print (A)

A = np.array([3,4,6])
B = A
B [1] = 7
print (A)

A = np.array([3,4,6])
B = np.copy(A)
B [1] = 7
print (A)

[3, 7, 6]
[3 7 6]
[3 4 6]


In [33]:
# list comprehension
new_random = np.random.random (9)
print('new_random: ', new_random)

new_random_1 = [new_random[i] for i in range (5, 9)]
print(new_random_1) #np.ndarray
new_list = [] #create empty list

for i in range (9):
    if new_random[i]>0.5:
        new_list +=[new_random[i]] #add values of new_random to our empty list
print('new_list:' ,new_list)

# as list comprehension
new_list2 = [new_random[i] for i in range (9) if new_random[i]>0.5]
print('new_list2: ', new_list2)

new_random:  [0.05837352 0.07036747 0.90102957 0.57939909 0.77290167 0.46239294
 0.14667182 0.9630377  0.00232341]
[0.46239294130819486, 0.14667182036559512, 0.9630376961695463, 0.0023234147644805025]
new_list: [0.9010295713084708, 0.5793990913108794, 0.7729016715433982, 0.9630376961695463]
new_list2:  [0.9010295713084708, 0.5793990913108794, 0.7729016715433982, 0.9630376961695463]


In [47]:
ListToSlice = np.array([1, 3, 5, 7, 9, 10, 15])
print(ListToSlice)
print(ListToSlice.reshape(-1,1))
np.arange(6).reshape((3, 2))

[ 1  3  5  7  9 10 15]
[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [10]
 [15]]


array([[0, 1],
       [2, 3],
       [4, 5]])

In [49]:
array = np.array([[11, 22], [33, 44]])
print ('mean: ', np.mean(array))

a = np.array([[2,3],[1,8]])
b = np.array([[5,6],[7,9]])
print('dot product: ', np.dot(a,b))

mean:  27.5
dot product:  [[31 39]
 [61 78]]
